### ISSUE TITLE
color code isn't working

### ISSUE THREAD

**Issue by min20120907** [Rauks/Minecraft-RCON#1]
I used this rcon, and my console can't show some specify information, e.g. factions plugin, it would show up the message below:

`

>  §r§6_______§r§r§6.[ §r§r§2Help for command "f"§r§2 §r§r§7[<] §r§61§r§6/§r§61§r§7 [>]§r§6 ].§r§6__________ §b/§r§bf§r§b §r§blist§r§b §r§3[page=1]§r§b §r§elist all factions §b/§r§bf§r§b §r§bfaction,f,show,who§r§b §r§3[faction=you]§r§b §r§eshow faction information §b/§r§bf§r§b §r§bplayer§r§b §r§3[player=you]§r§b §r§eshow player information §b/§r§bf§r§b §r§bjoin§r§b §r§3§r§b §r§3[player=you]§r§b §r§ejoin faction §b/§r§bf§r§b §r§cleave§r§b §r§eleave your faction §b/§r§bf§r§b §r§chome§r§b §r§3[faction=you]§r§b §r§eteleport to faction home §b/§r§bf§r§b §r§cmap§r§b §r§3[on/off=once]§r§b §r§eshow territory map §b/§r§bf§r§b §r§bcreate,new§r§b §r§3§r§b §r§ecreate new faction §b/§r§bf§r§b §r§bname§r§b §r§3§r§b §r§3[faction=you]§r§b §r§eset faction name §b/§r§bf§r§b §r§cdescription§r§b §r§3§r§b §r§echange faction description §b/§r§bf§r§b §r§bmotd§r§b §r§3[new=read]§r§b §r§efaction motd §b/§r§bf§r§b §r§csethome,sethome§r§b §r§3[faction=you]§r§b §r§eset the faction home §b/§r§bf§r§b §r§bunsethome§r§b §r§3[faction=you]§r§b §r§eunset faction home §b/§r§bf§r§b §r§binvite§r§b §r§emanage invites §b/§r§bf§r§b §r§bkick§r§b §r§3§r§b §r§ekick player from faction §b/§r§bf§r§b §r§btitle§r§b §r§3§r§b §r§3[title=]§r§b §r§eset player title §b/§r§bf§r§b §r§brank§r§b §r§3§r§b §r§3[action=show]§r§b §r§3[faction=their]§r§b §r§emanage/show ranks §b/§r§bf§r§b §r§bmoney§r§b §r§emanage faction money §b/§r§bf§r§b §r§cseeChunk,sc§r§b §r§3[active=toggle]§r§b §r§esee the chunk you stand in §b/§r§bf§r§b §r§cseeChunkOld,sco§r§b §r§esee the chunk you stand in §b/§r§bf§r§b §r§bterritorytitles,tt§r§b §r§3[on|off=toggle]§r§b §r§etoggle territory titles §b/§r§bf§r§b §r§bstatus§r§b §r§3[page=1]§r§b §r§3[faction=you]§r§b §r§3[sort=time]§r§b §r§eshow status §b/§r§bf§r§b §r§bclaim§r§b §r§eclaim faction territory §b/§r§bf§r§b §r§bunclaim§r§b §r§eunclaim faction territory §b/§r§bf§r§b §r§caccess§r§b §r§emanage access §b/§r§bf§r§b §r§brelation§r§b §r§emanage faction relations §b/§r§bf§r§b §r§bperm§r§b §r§echange faction permissions §b/§r§bf§r§b §r§bflag§r§b §r§emanage faction flags §b/§r§bf§r§b §r§cunstuck§r§b §r§eteleport to nearest wilderness §b/§r§bf§r§b §r§bexpansions§r§b §r§elist expansions §b/§r§bf§r§b §r§btax§r§b §r§eUse FactionsTax §b/§r§bf§r§b §r§bdynmap§r§b §r§eUse FactionsDynmap §b/§r§bf§r§b §r§boverride,admin§r§b §r§3[on/off=flip]§r§b §r§eenable override mode §b/§r§bf§r§b §r§bdisband§r§b §r§3[faction=you]§r§b §r§edisband faction §b/§r§bf§r§b §r§bpowerBoost§r§b §r§emanage powerboost §b/§r§bf§r§b §r§bsetpower,sp,setpower§r§b §r§3§r§b §r§3§r§b §r§eset power §b/§r§bf§r§b §r§bconfig§r§b §r§eedit config §b/§r§bf§r§b §r§bclean§r§b §r§eclean the factions database §b/§r§bf§r§b §r§bv,version§r§b §r§edisplay plugin version

`

**Comment by Rauks** [comment]
Fixed in #2
