### ISSUE TITLE
Weird character output.

### ISSUE THREAD

**Issue by JHBoricua** [Rauks/Minecraft-RCON#3]
I'm running this on my webserver and it is working fine but the output is all full of weird characters. I don't think it's necessarily an issue with this code but I'm hoping someone can point me in the right direction as my searches are not producing anything relevant.

For example, if I issue the command to list the plugins on the server, this is the output I get:

`
 Plugins (10): §aWorldEdit§f, §aVault§f, §aLaggRemover§f, §aWorldGuard§f, §aEssentials§f, §aEssentialsSpawn§f, §aEssentialsGeoIP§f, §aEssentialsChat§f, §aEssentialsAntiBuild§f, §aEssentialsProtect
`

So there's some obvious character encoding nuance at play but I don't know where to start troubleshooting it. I run several Wordpress sites on this webserver and I'm not having issues there. Any help is appreciated.

The webserver is a Centos 7 box with Apache 2.4.6 and PHP 7.1

**Comment by charliea21** [comment]
It’s not an issue. It’s colour encoding.

Minecraft uses the § character followed by a colour ID thingy.

It’s just that colour encoding isn’t supported.

*(I think)*

**Comment by JHBoricua** [comment]
Thanks @xXProGamerXx 

Looks like this was already fixed in the code but I had not done a pull on my end until now. It's right there on the main page under 'Fix color codes'. Ugh. Shoot me now.
